#!/bin/bash

if [ "$#" -eq 2 ]
then
    projectPath=$1
    templatePath=$2
    mkdir -p $projectPath
    cp -r $templatePath/. $projectPath
else
    echo "Please provide the following command-line arguments: <project_path> <path_to_template>"
fi
